/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.40
 * Generated at: 2021-01-26 04:15:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.chart;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class chart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html;charset=UTF-8\">\r\n");
      out.write("<title>Google Chart API</title>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-latest.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://www.gstatic.com/charts/loader.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t  setInterval(function(){ ajaxData(); }, 3000);\r\n");
      out.write("\r\n");
      out.write("function ajaxData() {\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl: './chartData',\r\n");
      out.write("\t\tdataType: \"json\",\r\n");
      out.write("\t\ttype: 'post',\r\n");
      out.write("\t\tasync: false,\r\n");
      out.write("\t\tsuccess: function(list) {\r\n");
      out.write("\t\t\tgoogle.charts.load('current', {'packages':['corechart']});\r\n");
      out.write("\t\t\tgoogle.charts.setOnLoadCallback(drawChart);\r\n");
      out.write("\t\t\tfunction drawChart() {\r\n");
      out.write("\t\t\t\tvar dataChart = [['Task', 'Hours per Day']];\r\n");
      out.write("\t\t\t\tif(list.length != 0) {\r\n");
      out.write("\t\t\t\t\t$.each(list, function(i, item){\r\n");
      out.write("\t\t\t\t\t\tdataChart.push([item.item, item.number]);\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}else {\r\n");
      out.write("\t\t\t\t\tdataChart.push(['입력해주세요', 1]);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tvar data = google.visualization.arrayToDataTable(dataChart);\r\n");
      out.write("\t\t\t\tvar view = new google.visualization.DataView(data);\r\n");
      out.write("\t\t\t\tvar options = {\r\n");
      out.write("\t\t\t\t\t\ttitle: \"제목\",\r\n");
      out.write("\t\t\t\t\t\twidth: 900, // 넓이 옵션\r\n");
      out.write("\t\t\t\t\t\theight: 200, // 높이 옵션\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\tvar chart1 = new google.visualization.PieChart(\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('piechart'));\r\n");
      out.write("\t\t\t\tvar chart2 = new google.visualization.LineChart(\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('linechart'));\r\n");
      out.write("\t\t\t\tvar chart3 = new google.visualization.BarChart(\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('barchart'));\r\n");
      out.write("\t\t\t\tvar chart4 = new google.visualization.ColumnChart(\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('columnchart'));\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tchart1.draw(view, options);\r\n");
      out.write("\t\t\t\tchart2.draw(view, options);\r\n");
      out.write("\t\t\t\tchart3.draw(view, options);\r\n");
      out.write("\t\t\t\tchart4.draw(view, options);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\tajaxData();\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <center>\r\n");
      out.write("        <h1>Google Chart</h1> \r\n");
      out.write("        <input type=\"button\" value=\"데이터호출\" onclick=\"myFunction()\"/>\r\n");
      out.write("        &nbsp;&nbsp;\r\n");
      out.write("\t    <a href=\"../\">인덱스</a>\r\n");
      out.write("\t    <br/><br/>\r\n");
      out.write("\t   \r\n");
      out.write("\t\t<div id=\"piechart\"></div>\r\n");
      out.write("\t\t<div id=\"linechart\"></div>\r\n");
      out.write("\t\t<div id=\"barchart\"></div>\r\n");
      out.write("\t\t<div id=\"columnchart\"></div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
